#!/usr/bin/env node
// =====================================================================
//  export-seed.mjs — reads the prototype's data.js (READ-ONLY, never
//  modified) and writes:
//    supabase/seed.sql          idempotent upserts for every catalogue entity
//    supabase/seed-users.json   the seeded people (no secrets) for seed-users.mjs
//
//  Usage:  node scripts/export-seed.mjs [path/to/prototype]   (default ../revnu)
// =====================================================================
import fs from "node:fs";
import path from "node:path";
import vm from "node:vm";
import { fileURLToPath } from "node:url";
import { TABLES, normaliseAssetsDeep } from "../lib/data/mappers.js";

const here = path.dirname(fileURLToPath(import.meta.url));
const root = path.resolve(here, "..");
const protoDir = path.resolve(process.argv[2] || path.join(root, "..", "revnu"));
const dataJs = path.join(protoDir, "data.js");
if (!fs.existsSync(dataJs)) { console.error("prototype data.js not found at", dataJs); process.exit(1); }

// ---- run data.js in a sandbox with an empty localStorage --------------
const src = fs.readFileSync(dataJs, "utf8");
const storage = { getItem: () => null, setItem: () => {}, removeItem: () => {}, key: () => null, length: 0 };
const sandbox = { window: {}, localStorage: storage, sessionStorage: storage, console, Intl, Date, JSON, Math, RegExp, Object, Array, String, Number, Blob: class {}, document: undefined };
sandbox.window.localStorage = storage;
vm.createContext(sandbox);
vm.runInContext(src, sandbox, { filename: "data.js" });
const D = sandbox.window.REVNU_DATA;
if (!D) { console.error("REVNU_DATA did not load"); process.exit(1); }

// ---- constants that live in revnu.jsx (Revnu HQ levels) ----------------
const REVNU_ROLES = [
  { id: "super_admin", en: "Super Admin", ar: "مدير عام",    perms: ["developers","financials","orders","team","settings"] },
  { id: "admin",       en: "Admin",       ar: "مدير",        perms: ["developers","financials","orders"] },
  { id: "team",        en: "Team",        ar: "عضو فريق",     perms: ["orders"] },
];
const REVNU_PERMS = [
  { id: "developers", en: "Manage developers",      ar: "إدارة المطوّرين" },
  { id: "orders",     en: "View orders & payments", ar: "عرض الطلبات والمدفوعات" },
  { id: "financials", en: "View financials",        ar: "عرض البيانات المالية" },
  { id: "team",       en: "Manage team",            ar: "إدارة الفريق" },
  { id: "settings",   en: "Platform settings",      ar: "إعدادات المنصّة" },
];

// ---- SQL literal helpers ------------------------------------------------
const q = (s) => "'" + String(s).replace(/'/g, "''") + "'";
function lit(v, col) {
  if (v === undefined || v === null) return "null";
  if (Array.isArray(v) && (col.endsWith("_ar") || ["materials","includes","level_names","palette","blocks","perms"].includes(col))) {
    return v.length ? "array[" + v.map((x) => q(x)).join(",") + "]::text[]" : "'{}'::text[]";
  }
  if (typeof v === "object") return q(JSON.stringify(v)) + "::jsonb";
  if (typeof v === "boolean") return v ? "true" : "false";
  if (typeof v === "number") return Number.isFinite(v) ? String(v) : "null";
  return q(v);
}
// Identifiers are always quoted: some column names are reserved words in Postgres (e.g. "when").
const qId = (c) => '"' + String(c).replace(/"/g, '""') + '"';
function upsert(table, rows, pk) {
  if (!rows.length) return `-- ${table}: nothing to seed\n`;
  const cols = [...new Set(rows.flatMap((r) => Object.keys(r)))];
  const vals = rows.map((r) => "(" + cols.map((c) => lit(r[c], c)).join(", ") + ")").join(",\n  ");
  const upd = cols.filter((c) => !pk.includes(c)).map((c) => `${qId(c)} = excluded.${qId(c)}`).join(", ");
  return `insert into public.${table} (${cols.map(qId).join(", ")}) values\n  ${vals}\non conflict (${pk.map(qId).join(", ")}) do update set ${upd || qId(pk[0]) + " = excluded." + qId(pk[0])};\n`;
}

// ---- build rows --------------------------------------------------------
const rows = (kind, list, extra = (x) => x) => list.map((o, i) => TABLES[kind].m.toRow(extra(normaliseAssetsDeep(o), i)));

const out = [];
out.push("-- Generated by scripts/export-seed.mjs from the prototype data.js — do not edit by hand.\n");
out.push("begin;\n");
out.push(upsert("dev_perms",   rows("devPerms",   D.DEV_PERMS.map((p, i) => ({ ...p, sort: i }))), ["id"]));
out.push(upsert("dev_roles",   rows("devRoles",   D.DEV_ROLES.map((r, i) => ({ ...r, sort: i }))), ["id"]));
out.push(upsert("revnu_perms", rows("revnuPerms", REVNU_PERMS.map((p, i) => ({ ...p, sort: i }))), ["id"]));
out.push(upsert("revnu_roles", rows("revnuRoles", REVNU_ROLES.map((r, i) => ({ ...r, sort: i }))), ["id"]));
out.push(upsert("contract_vars", rows("contractVars", D.CONTRACT_VARS.map((v, i) => ({ ...v, block: !!v.block, sort: i }))), ["code"]));

const devs = D.DEVELOPERS.map(({ commissionLadder, ...d }) => d);
out.push(upsert("developers", rows("developers", devs), ["id"]));
const ladder = D.DEVELOPERS.flatMap((d) => (d.commissionLadder || []).map((l, i) => ({ ...l, developerId: d.id, sort: i })));
out.push(upsert("commission_levels", rows("commissionLevels", ladder), ["developer_id", "id"]));

out.push(upsert("projects", rows("projects", D.PROJECTS.map((p) => ({ ...p, revnuTerms: p.revnuTerms || null }))), ["id"]));
out.push(upsert("unit_types", rows("unitTypes", D.UNIT_TYPES), ["id"]));
out.push(upsert("units", rows("units", D.UNITS), ["number"]));
out.push(upsert("design_styles", rows("designStyles", D.DESIGN_STYLES), ["id"]));
out.push(upsert("packages", rows("packages", D.PACKAGES), ["id"]));
out.push(upsert("smart_home", rows("smartHome", D.SMART_HOME), ["id"]));
out.push(upsert("ops_models", rows("opsModels", D.OPS_MODELS), ["id"]));
out.push(upsert("construction_milestones", rows("constructionMilestones", D.CONSTRUCTION_MILESTONES), ["id"]));
out.push(upsert("payment_plans", rows("paymentPlans", D.PAYMENT_PLANS), ["id"]));
out.push(upsert("contract_templates", rows("contractTemplates", D.CONTRACTS), ["id"]));
out.push("commit;\n");

fs.writeFileSync(path.join(root, "supabase", "seed.sql"), out.join("\n"), "utf8");

// ---- people (auth users are created by scripts/seed-users.mjs) ----------
const people = D.USERS.map((u) => ({
  legacyId: u.id, developerId: u.developerId || null, name: u.name, nameAr: u.nameAr || null, email: u.email.toLowerCase(),
  role: u.role, roleAr: u.roleAr || null, roleId: u.roleId || null, perms: u.perms || null,
  commissionLevelId: u.commissionLevelId || null, reportsTo: u.reportsTo || null, assignedProjectIds: u.assignedProjectIds || [],
}));
fs.writeFileSync(path.join(root, "supabase", "seed-users.json"), JSON.stringify(people, null, 2), "utf8");

console.log(`seed.sql: developers=${devs.length} projects=${D.PROJECTS.length} unitTypes=${D.UNIT_TYPES.length} units=${D.UNITS.length} designs=${D.DESIGN_STYLES.length} packages=${D.PACKAGES.length} smart=${D.SMART_HOME.length} ops=${D.OPS_MODELS.length} milestones=${D.CONSTRUCTION_MILESTONES.length}`);
console.log(`seed-users.json: ${people.length} people`);
